# Generated by Django 3.1 on 2021-03-20 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('student_fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('student_age', models.IntegerField()),
                ('student_date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet_name', models.CharField(max_length=50)),
                ('sweet_color', models.CharField(max_length=50)),
                ('sweet_shape', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='studentcourse',
            fields=[
                ('student_course_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_course', to='lekshmiapp.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_course', to='lekshmiapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_courses',
            field=models.ManyToManyField(related_name='student', through='lekshmiapp.studentcourse', to='lekshmiapp.course'),
        ),
        migrations.CreateModel(
            name='PurchaseMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseno', models.CharField(max_length=20)),
                ('purchasedate', models.IntegerField()),
                ('invoiceno', models.CharField(max_length=20)),
                ('invoicedate', models.DateField()),
                ('vendor', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='lekshmiapp.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=7)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=7)),
                ('purchaseitem', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, to='lekshmiapp.itemmaster')),
                ('purchaseno', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='lekshmiapp.purchasemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_fname', models.CharField(help_text='This is first name of Employee', max_length=50, verbose_name='First Name')),
                ('employee_lname', models.CharField(max_length=50)),
                ('employee_adharnos', models.CharField(max_length=20)),
                ('employee_age', models.IntegerField(default=0)),
                ('employee_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lekshmiapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('city_name', models.CharField(default=1, max_length=30)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lekshmiapp.state')),
            ],
        ),
    ]
