# Generated by Django 3.1 on 2021-04-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekshmiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
